name: xiaoman-k230-ci

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

env:
  xuantie_toolchain: https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource//1721095219235//
  toolchain_file_name: Xuantie-900-gcc-linux-6.6.0-glibc-x86_64-V2.10.1-20240712.tar.gz
  #mainline_toolchain: https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2023.10.18
  #mainline_toolchain_file_name: riscv64-glibc-ubuntu-22.04-gcc-nightly-2023.10.18-nightly.tar.gz
  wget_alias: 'wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0'
  ARCH: riscv
  CROSS_COMPILE: riscv64-unknown-linux-gnu-
  KBUILD_BUILD_USER: builder
  KBUILD_BUILD_HOST: revyos-riscv-builder
  KDEB_COMPRESS: xz
  KDEB_CHANGELOG_DIST: unstable
  OUTPUT: output


jobs:
  mkrootfs:
    strategy:
      fail-fast: false
      
    runs-on: ubuntu-22.04
    steps:
      - name: Create Timestamp
        run: |
              echo "BUILD_ID=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV
              echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
